  CREATE TABLE "FCERNY"."TAB1"
   (	"ID" NUMBER,
	"DESCRIPTION" VARCHAR2(50) COLLATE "USING_NLS_COMP",
	CONSTRAINT "TAB1_PK" PRIMARY KEY ("ID")
  USING INDEX
  PCTFREE 10 INITRANS 20 MAXTRANS 255 LOGGING
  TABLESPACE "DATA"  ENABLE
   ) DEFAULT COLLATION "USING_NLS_COMP"  SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 10 NOCOMPRESS LOGGING
  TABLESPACE "DATA";
