  CREATE UNIQUE INDEX "FRANKCERNY"."BSA_NON_FIXED_QUANTITY_SUPPLY" ON "FRANKCERNY"."BSA_NON_FIXED_QUANTITY_SUPPLY" ("NAME","DATEPURCHASED")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  TABLESPACE "APEX_1900686847875038";
