  CREATE UNIQUE INDEX "DEV_WS"."BSA_SINGLE_USE_SUPPLY_UK" ON "DEV_WS"."BSA_SINGLE_USE_SUPPLY" ("PROJECT_ID","NAME")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS";
