--liquibase formatted sql

--changeset fcerny:1
create table bsa_audit_log (
    id                             number generated by default on null as identity constraint bsa_audit_log_id_pk primary key,
    date_logged                    date not null,
    table                          varchar2(50 char) not null,
    project_id                     number,
    operation                      varchar2(100 char) not null,
    description                    varchar2(500 char) not null
);