--liquibase formatted sql

--changeset fcerny:1
create table bsa_tax_income (
    id                             number generated by default on null as identity constraint bsa_tax_income_id_pk primary key,
    year                           varchar2(4) not null,
    estimatedIncome                number not null,
    actualIncome                   number
);