# Playbook to rollback ORDS installation into a pre-configured Tomcat instance
# @date: 3/15/2022
# @author: Frank Cerny
- name: Rollback ORDS installation into Tomcat (RHEL)
  hosts: APEX
  remote_user: ansible
  become: true