
  ALTER TABLE "DEV_WS"."BSA_PROJECT_FIXED_QUANTITY_SUPPLY" ADD CONSTRAINT "BSA_PROJECT_FIX_QUANT_SUPP_FK" FOREIGN KEY ("SUPPLY_ID")
	  REFERENCES "DEV_WS"."BSA_FIXED_QUANTITY_SUPPLY" ("ID") ON DELETE CASCADE ENABLE