
  ALTER TABLE "FCERNY"."BSA_PROJECT_FIXED_QUANTITY_SUPPLY" ADD CONSTRAINT "BSA_PROJECT_FIX_QUANT_SUPP_FK" FOREIGN KEY ("SUPPLY_ID")
	  REFERENCES "FCERNY"."BSA_FIXED_QUANTITY_SUPPLY" ("ID") ON DELETE CASCADE ENABLE;