
  ALTER TABLE "FRANKCERNY"."BSA_PROJECT_FIXED_QUANTITY_SUPPLY" ADD CONSTRAINT "BSA_PROJECT_FIX_QUANT_SUPP_FK" FOREIGN KEY ("SUPPLY_ID")
	  REFERENCES "FRANKCERNY"."BSA_FIXED_QUANTITY_SUPPLY" ("ID") ON DELETE CASCADE ENABLE